# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '首页活动类型表',
                'verbose_name_plural': '首页活动类型表',
                'db_table': 'my_activtytype',
            },
        ),
        migrations.CreateModel(
            name='B_Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField()),
            ],
            options={
                'verbose_name': '管理员表',
                'verbose_name_plural': '管理员表',
                'db_table': 'my_admin',
            },
        ),
        migrations.CreateModel(
            name='B_Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('principal', models.CharField(max_length=20)),
                ('telecom', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name': '供应商表',
                'verbose_name_plural': '供应商表',
                'db_table': 'my_suppliers',
            },
        ),
        migrations.CreateModel(
            name='C_UserInfo',
            fields=[
                ('user_account', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_pic', models.ImageField(default='head/man.png', upload_to='head/')),
                ('user_gender', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=1, verbose_name='性别')),
                ('user_firstname', models.CharField(blank=True, default='', max_length=20, verbose_name='姓')),
                ('user_secondname', models.CharField(blank=True, default='', max_length=20, verbose_name='名')),
                ('user_telecom', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('user_phone', models.CharField(max_length=11, verbose_name='手机')),
                ('user_company', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('user_addr', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user_lastlogin', models.DateTimeField(null=True, verbose_name='上次登录')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '客户表',
                'verbose_name_plural': '客户表',
                'db_table': 'my_users',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '购物车表',
                'verbose_name_plural': '购物车表',
                'db_table': 'my_cart',
            },
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20, unique=True, verbose_name='类别')),
            ],
            options={
                'verbose_name': '商品类别表',
                'verbose_name_plural': '商品类别表',
                'db_table': 'my_goodcategory',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('good_name', models.CharField(db_index=True, max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_orgin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('good_shortinfo', models.TextField(default=' ', null=True)),
                ('good_info', tinymce.models.HTMLField()),
                ('good_pic', models.ImageField(upload_to='goods/')),
                ('count_sell', models.IntegerField(default=0)),
                ('isdelete', models.BooleanField(default=False)),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.GoodCategory')),
                ('good_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_index.ActivityType')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'my_goods',
            },
        ),
        migrations.CreateModel(
            name='IndexPageGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='goods/')),
                ('desc', models.CharField(max_length=50)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.Goods')),
            ],
            options={
                'verbose_name': '首页活动商品表',
                'verbose_name_plural': '首页活动商品表',
                'db_table': 'my_indexpagegoods',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('counts', models.IntegerField(default=1)),
                ('state', models.CharField(max_length=20)),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('notes', models.TextField()),
                ('score', models.IntegerField()),
                ('pay', models.CharField(max_length=10)),
                ('isdelete', models.BooleanField(default=False)),
                ('isdebt', models.BooleanField(default=False)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.Goods')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.C_UserInfo')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'my_orders',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('counts', models.IntegerField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('notes', models.TextField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.Goods')),
                ('supplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.B_Supplier')),
            ],
            options={
                'verbose_name': '进货表',
                'verbose_name_plural': '进货表',
                'db_table': 'my_purchase',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.C_UserInfo'),
        ),
    ]
