# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_userinfo',
            name='user_gender',
            field=models.CharField(choices=[('男', '男'), ('男', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
