# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_index', '0003_auto_20170804_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.IntegerField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.Goods')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'my_orderInfo',
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='counts',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='gid',
        ),
        migrations.AddField(
            model_name='orders',
            name='ototal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='c_userinfo',
            name='user_gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_index.Orders'),
        ),
    ]
