# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_index', '0004_auto_20170807_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
