# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_index', '0005_auto_20170807_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orgintotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
